// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"api-reference.mdx": () => import("../src/content/docs/api-reference.mdx?collection=docs"), "architecture.mdx": () => import("../src/content/docs/architecture.mdx?collection=docs"), "dashboard.mdx": () => import("../src/content/docs/dashboard.mdx?collection=docs"), "data-pipeline-architecture.mdx": () => import("../src/content/docs/data-pipeline-architecture.mdx?collection=docs"), "database-architecture.mdx": () => import("../src/content/docs/database-architecture.mdx?collection=docs"), "deployment.mdx": () => import("../src/content/docs/deployment.mdx?collection=docs"), "evaluation.mdx": () => import("../src/content/docs/evaluation.mdx?collection=docs"), "index.mdx": () => import("../src/content/docs/index.mdx?collection=docs"), "interview-questions.mdx": () => import("../src/content/docs/interview-questions.mdx?collection=docs"), "legacy-migration-guide.mdx": () => import("../src/content/docs/legacy-migration-guide.mdx?collection=docs"), "multi-agent.mdx": () => import("../src/content/docs/multi-agent.mdx?collection=docs"), "multilingual-translation.mdx": () => import("../src/content/docs/multilingual-translation.mdx?collection=docs"), "observability.mdx": () => import("../src/content/docs/observability.mdx?collection=docs"), "rag-pipeline.mdx": () => import("../src/content/docs/rag-pipeline.mdx?collection=docs"), "roadmap.mdx": () => import("../src/content/docs/roadmap.mdx?collection=docs"), "security.mdx": () => import("../src/content/docs/security.mdx?collection=docs"), "skills.mdx": () => import("../src/content/docs/skills.mdx?collection=docs"), "agents/AGENT_SYSTEM_OVERVIEW.mdx": () => import("../src/content/docs/agents/AGENT_SYSTEM_OVERVIEW.mdx?collection=docs"), "agents/approval_agent.mdx": () => import("../src/content/docs/agents/approval_agent.mdx?collection=docs"), "agents/classifier_agent.mdx": () => import("../src/content/docs/agents/classifier_agent.mdx?collection=docs"), "agents/formatter_agent.mdx": () => import("../src/content/docs/agents/formatter_agent.mdx?collection=docs"), "agents/reflection_agent.mdx": () => import("../src/content/docs/agents/reflection_agent.mdx?collection=docs"), "agents/retrieval_agent.mdx": () => import("../src/content/docs/agents/retrieval_agent.mdx?collection=docs"), "agents/reviewer_agent.mdx": () => import("../src/content/docs/agents/reviewer_agent.mdx?collection=docs"), "agents/router_agent.mdx": () => import("../src/content/docs/agents/router_agent.mdx?collection=docs"), "agents/tracker_agent.mdx": () => import("../src/content/docs/agents/tracker_agent.mdx?collection=docs"), }),
};
export default browserCollections;